platform :ios, '5.0'

pod 'cocos2d', '2.1-rc2'
pod 'AFNetworking', '1.2.1'
pod 'MKNetworkKit', '0.87'
pod 'JSONKit', '1.5pre'
pod 'SVProgressHUD', '0.9'
pod 'EGOTableViewPullRefresh', '0.1.0'
pod 'RegexKitLite'
pod 'CocoaLumberjack', '1.6.2'