platform :ios, '5.0'

pod 'AFNetworking', '1.2.1'
pod 'JSONKit', '1.5pre'
pod 'SVProgressHUD', '0.9'
pod 'EGOTableViewPullRefresh', '0.1.0'
pod 'DLStarRating', '1.1'
pod 'ZGCountDownTimer', '0.0.1'
pod 'FTUtils', '1.1.1'
pod 'JGAFImageCache'
pod 'QuadCurveMenu'
pod 'RegexKitLite'
pod 'cocos2d', '2.1-rc2'